### ISSUE TITLE
Parse error: syntax error, unexpected in ..../src/Robo/RoboTasks.php on line 132

### ISSUE THREAD

**Issue by arteugen** [mwr/magedeploy2#10]
Hey @mwr ,

with new version 2.3.0 i got an error while artifact building:

`Parse error: syntax error, unexpected '=' in /builds/MairDumont/magento2-shop/deployment/vendor/mwltr/magedeploy2/src/Robo/RoboTasks.php on line 132`

are you sure that the code in line 132 right structured ?

Best regards,
Eugen

**Comment by mwr** [comment]
Hi @arteugen ,

you are referring to this piece of code?:
`[$branch, $revision] = explode('@', $branch);`
https://github.com/mwr/magedeploy2/blob/develop/src/Robo/RoboTasks.php#L132

It is valid assignment in php7.1, take a look here: https://wiki.php.net/rfc/short_list_syntax

Which PHP version are you working with?

Maybe the module should have the php version as a requirement in the composer.json

**Comment by arteugen** [comment]
Close as works on new PHP 7.1
